In [1]:
import numpy as np

In [33]:
myarr = np.array([[1,2,3]], np.int64)

In [28]:
myarr

array([[1, 2, 3]], dtype=int64)

In [29]:
myarr.shape

(1, 3)

In [30]:
myarr.dtype

dtype('int64')

In [34]:
myarr[0]

array([1, 2, 3], dtype=int64)

In [37]:
myarr[0,2] = 192

In [38]:
myarr

array([[  1,   2, 192]], dtype=int64)

***My_Python***

**My Python**

*My Python*

***my python***

In [63]:
listarray = np.array([[1,2,3],[3,4,5,],[5,3,2],[2,5,6]])

In [64]:
listarray

array([[1, 2, 3],
       [3, 4, 5],
       [5, 3, 2],
       [2, 5, 6]])

In [67]:
listarray[3,2]

6

In [59]:
listarray.shape

(1, 4, 3)

In [60]:
listarray.size

12

In [62]:
listarray.dtype

dtype('int32')

In [68]:
np.array({1,2,3,4})

array({1, 2, 3, 4}, dtype=object)

In [75]:
np.array([2,3,4,2])

array([2, 3, 4, 2])

In [81]:
zero = np.zeros([3,2])

In [82]:
zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
np.arange(27)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [92]:
lspace = np.linspace(2,40,15)

In [94]:
lspace

array([ 2.        ,  4.71428571,  7.42857143, 10.14285714, 12.85714286,
       15.57142857, 18.28571429, 21.        , 23.71428571, 26.42857143,
       29.14285714, 31.85714286, 34.57142857, 37.28571429, 40.        ])

In [98]:
lspace.size

15

In [99]:
one = np.ones((1,4))

In [100]:
one

array([[1., 1., 1., 1.]])

In [103]:
emp = np.empty((1,3))

In [104]:
emp

array([[9.67525468e-313, 0.00000000e+000, 4.94065646e-324]])

In [107]:
ide = np.identity(45)

In [106]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0

In [108]:
ide.shape

(45, 45)

In [113]:
arr = np.arange(48)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [115]:
arr.reshape(2,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        40, 41, 42, 43, 44, 45, 46, 47]])

In [116]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [117]:
arr.shape

(48,)

In [118]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [119]:
arr.shape

(48,)

In [120]:
x = [[1,2],[2,3],[3,4]]

In [121]:
x

[[1, 2], [2, 3], [3, 4]]

In [122]:
arr = np.array(x)

In [123]:
arr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [127]:
arr.sum(axis=0)

array([6, 9])

In [128]:
arr.max()

4

In [129]:
arr.min()

1

In [131]:
arr.sum(axis=1)

array([3, 5, 7])

In [132]:
arr

array([[1, 2],
       [2, 3],
       [3, 4]])

In [133]:
arr.T

array([[1, 2, 3],
       [2, 3, 4]])