In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
arr = [[1,2],[2,3],[4,3]]

In [4]:
arra = np.array(arr)

In [5]:
arra

array([[1, 2],
       [2, 3],
       [4, 3]])

In [6]:
arra.T

array([[1, 2, 4],
       [2, 3, 3]])

In [7]:
arra

array([[1, 2],
       [2, 3],
       [4, 3]])

In [8]:
a=arra.flat

In [9]:
for i in a:
    print(i)

1
2
2
3
4
3


In [10]:
arra.ndim

2

In [11]:
arra.shape

(3, 2)

In [12]:
sania = np.array([[1,2],[2,3],[4,3]])

In [13]:
sania

array([[1, 2],
       [2, 3],
       [4, 3]])

In [14]:
sania.argmax(axis=1)

array([1, 1, 0], dtype=int64)

In [15]:
sania.argmin(axis=1)

array([0, 0, 1], dtype=int64)

In [16]:
sania.argsort(axis=0)

array([[0, 0],
       [1, 1],
       [2, 2]], dtype=int64)

In [17]:
sania.size

6

In [18]:
sania.shape

(3, 2)

In [19]:
sania.dtype

dtype('int32')

In [21]:
sania

array([[1, 2],
       [2, 3],
       [4, 3]])

In [20]:
sania.ravel()

array([1, 2, 2, 3, 4, 3])

In [23]:
sania.T

array([[1, 2, 4],
       [2, 3, 3]])

In [26]:
a =sania.T

In [34]:
a

array([[1, 2, 4],
       [2, 3, 3]])

In [35]:
a.size

6

In [ ]:
a.reshape(a)