In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.Series([1,2,3,4])
df

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
df.dtypes

dtype('int64')

In [4]:
df.to_list()

[1, 2, 3, 4]

In [5]:
dn = np.array([1,2,3])
dn

array([1, 2, 3])

In [6]:
dn.tolist()

[1, 2, 3]

In [7]:
dn

array([1, 2, 3])

In [8]:
a = [1,2,3,4]

In [9]:
b = np.array(a)
b

array([1, 2, 3, 4])

In [10]:
c = pd.Series(a)

In [11]:
c

0    1
1    2
2    3
3    4
dtype: int64

In [12]:
ser1  = [2, 4, 6, 8, 10]
ser2 = [1, 3, 5, 7, 9]
a = pd.Series(ser1)
b = pd.Series(ser2)
print(a)
print(b)

0     2
1     4
2     6
3     8
4    10
dtype: int64
0    1
1    3
2    5
3    7
4    9
dtype: int64


In [13]:
ser1 + ser2

[2, 4, 6, 8, 10, 1, 3, 5, 7, 9]

In [14]:
a + b

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [15]:
a * b

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [16]:
a / b

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [17]:
a - b

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [18]:
a.dtypes
b.dtypes

dtype('int64')

In [19]:
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])

In [20]:
ds1 == ds2

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [21]:
ds1 >= ds2

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [22]:
ds1 <= ds2

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [23]:
dic1 = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
print(type(dic1))
print(dic1)

<class 'dict'>
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}


In [24]:
dic = pd.Series({'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800})

In [25]:
print(type(dic))
print(dic)

<class 'pandas.core.series.Series'>
a    100
b    200
c    300
d    400
e    800
dtype: int64


In [26]:
a = np.array([10, 20, 30, 40, 50])
type(a)

numpy.ndarray

In [27]:
b = pd.Series(a)

In [28]:
print(type(b))
print(b)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int32


In [30]:
a = pd.Series([100,200,"python",300.12,400])
a

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [31]:
a.iloc[2] = "NaN"

In [32]:
a

0       100
1       200
2       NaN
3    300.12
4       400
dtype: object

In [33]:
a = a.astype(float)

In [34]:
a

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [50]:
dic = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}

In [51]:
df = pd.DataFrame(dic)

In [53]:
df.dtypes

col1    int64
col2    int64
col3    int64
dtype: object

In [54]:
df['col1']

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64

In [59]:
ds = pd.Series([100,200,"python",300.12,400])
ds

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [60]:
arr = np.array(ds)

In [61]:
arr

array([100, 200, 'python', 300.12, 400], dtype=object)

In [66]:
type(arr.tolist())

list

In [95]:
dic1 = pd.Series([["Red", "Green", "White"], ["Red", "Black"], ["Yellow"]])

In [96]:
type(dic1)

pandas.core.series.Series

In [102]:
import pandas as pd
s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']])
print("Original Series of list")
print(s)
s = s.apply(pd.Series).stack()
print("One Series")
print(s)

Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0  0       Red
   1     Green
   2     White
1  0       Red
   1     Black
2  0    Yellow
dtype: object


In [122]:
king = pd.Series(['100','200',"python",'300.12','400'])
king

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [127]:
d.sort_values()

0       100
1       200
3    300.12
4       400
2    python
dtype: object

In [128]:
ding = pd.Series(['100','200',"python",'300.12','400'])

In [140]:
ding.append(pd.Series(['334','423']))

C:\Users\Faaz Ali\AppData\Local\Temp\ipykernel_5016\2077095338.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ding.append(pd.Series(['334','423']))


0       100
1       200
2    python
3    300.12
4       400
0       334
1       423
dtype: object

In [144]:
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print(s)
x = s.reindex(index=['A', 'B', 'E','D','C'])
print(x)

A    1
B    2
C    3
D    4
E    5
dtype: int64
A    1
B    2
E    5
D    4
C    3
dtype: int64


In [147]:
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3], index = [0,1,2,3,4,5,6,7,8,9,10])
print(s)
s.describe()

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64


count    11.000000
mean      4.818182
std       2.522625
min       1.000000
25%       3.000000
50%       5.000000
75%       6.500000
max       9.000000
dtype: float64

In [153]:
s = pd.Series([1,2,3,4,5,6,7,8,9,5,3])
d = s.mean()
f = s.median()
q = s.std()
print(d)
print(f)
print(q)

4.818181818181818
5.0
2.522624895547565


In [158]:
s1 = pd.Series([1,2,3, 4 ,5])
s2 = pd.Series([2,3,4,8,10])
s

's1s2'